### ISSUE TITLE
Update color palette

### ISSUE THREAD

**Issue by abrahamnavas** [Stratio/egeo-web#83]
The status color palette has been modified, so is mandatory to update it as the following images:

Former scheme:
![old_scheme](https://cloud.githubusercontent.com/assets/7441029/26353702/e9214dd6-3fc1-11e7-810a-ede6432ee8a6.png)

Updated scheme:
![new_scheme](https://cloud.githubusercontent.com/assets/7441029/26353708/f3666768-3fc1-11e7-80d3-0a5686bdc08e.png)

You can take those new values straight from the [prototype](https://zpl.io/Z2vrOTu).

**Comment by alexrchies** [comment]
This task should be moved to [Egeo UI Base](https://github.com/Stratio/egeo-ui-base).
